import React, { useContext, useEffect } from "react";
import { Context } from "../../context/Context";

const data = [
  {
    id: 1,
    title: "Gosau Log House",
    name: "44 Sardine Slow Life Houseboat - Carsibor Island",
    rating: 4.25,
    num_reviews: 147,
    city: "Świnoujście, Województwo zachodniopomorski",
    country: "Poland",
    price: 106,
    superhost: "true",
    host: "Sebastian",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Nov25-30",
    type: "houseboat",
    images: [
      "https://a0.muscache.com/im/pictures/4532d3d4-dd10-472c-bc9b-fda35645f074.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/f080ece9-3d5d-4686-b1f3-fbd66ae8f181.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/42943aae-a61d-44cf-ac74-032872b406ec.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e57df990-3268-4c4e-8fbf-b430675d6696.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a9add02a-76e5-4ec3-b25f-c6bfc00ca512.jpg?im_w=720",
    ],
    latlong: ["53.86329846276284", "14.286039249140556"],
    description:
      "The island is incredibly picturesque. The green area is surrounded by old-growth pine trees, old pine trees, oak trees, donkeys, donkeys, donkeys, and blue. They have long and lovely hiking trails through the forests and woods. Karsibor is an important hub of water sports and fishing. It is a unique cycling experience. The village houses a 15th-century church.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },
  {
    id: 2,
    title: "Beautiful cottage on magical lake",
    name: "Private room in serviced apartment hosted by Sylvia",
    rating: 4.7,
    num_reviews: 102,
    city: "Schladming, Steiermark",
    country: "Austria",
    price: 316,
    superhost: "true",
    host: "Sylvia",
    guests: 4,
    bedrooms: 2,
    beds: 4,
    bath: 1,
    date: "Nov28-30",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-585198300657215100/original/3ed0cf4d-6016-4485-be4d-6f1a8ab758ff.jpeg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-585198300657215100/original/17f6e5ac-007d-4664-8dcc-f9a254bcb73f.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-585198300657215100/original/0b6775a6-a0bc-4d8f-9602-ace39701114e.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-585198300657215100/original/e6a2f788-2967-4cb8-8f71-195425ab3194.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-585198300657215100/original/cf30fcd4-c31b-4de3-b86f-f16caa264c7b.jpeg?im_w=720",
    ],
    latlong: ["47.372987385108416", "13.724369913599194"],
    description:
      "In the 62m² apartment with sauna, you can live wonderfully with four people. Including terrace & balcony with roof stone view. You can order your breakfast with regional delicacies as you please. The kitchen is fully equipped with an oven, dishwasher, etc. Upon arrival, you will find coffee, tea, salt, pepper & sugar. We will tell you about our recommendations for food.Located directly on the ski slope. Shoe room, ski cellar, bike room and sockets for e-bike & e-car available.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },
  {
    id: 3,
    title: "Maja's Hideaway",
    name: "Entire rental unit hosted by Julia",
    rating: 4.12,
    num_reviews: 144,
    city: "Geisenheim, Hessen",
    country: "Germany",
    price: 76,
    superhost: "false",
    host: "Julia",
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bath: 1,
    date: "Nov17-23",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-597806156879860866/original/523e2c37-ef4b-44af-85ea-24398be19b2b.jpeg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-597806156879860866/original/e630f0a7-68cb-4387-a1c5-5950cb28d9c0.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-597806156879860866/original/a053138b-8366-4187-ab26-7a05e6344c4c.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-597806156879860866/original/25ebc33d-a063-4f1b-b553-af53e0e80edd.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/a4e0bb21-d01d-4457-815d-1398123ca9eb.jpg?im_w=720",
    ],
    latlong: ["49.970337179185584", "7.945917259737131"],
    description:
      "Go on holiday where the late harvest was discovered - in Johannisberg, a stone's throw from the Johannisberg Abbey. The 70 sqm light-flooded jewel on the 2nd floor is centrally located and invites you to hikes and wine tastings.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },
  {
    title: "Under Cupra",
    name: "Entire home hosted by Jon",
    rating: 4.92,
    num_reviews: 104,
    city: "Kullavik, Hallands län",
    country: "Sweden",
    price: 125,
    superhost: "true",
    host: "Jon",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bath: 1,
    date: "Dec5-30",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/ccb54791-b4cd-4a04-a489-892d5be13cff.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-24173392/original/b570ed5b-0560-4f9c-8ec8-9950c328c48a.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/71e30706-90a4-4fdf-bac2-5c540f81dd12.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8f58649a-efc6-4ab0-a055-e08788ea6a16.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/5fe862df-a7b4-4bc6-8999-cb4d14fdecae.jpg?im_w=720",
    ],
    latlong: ["49.970337179185584", "7.945917259737131"],
    description:
      "Newly built 42 square meters two-story souterrain house surrounded by Swedish west coast nature and the beautiful sea! With a private road, parking space, and dedicated EV charging station, the house is located alone at the edge of the property. Surrounded by the typical Swedish west coast nature, overlooking both the western sea horizon and the beautiful archipelago.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Holiday home ",
    name: "Entire home hosted by Marieke",
    rating: 4.26,
    num_reviews: 17,
    city: "Sint-Oedenrode, Noord-Brabant",
    country: "Netherlands",
    price: 355,
    superhost: "false",
    host: "Marieke",
    guests: 8,
    bedrooms: 4,
    beds: 6,
    bath: 2,
    date: "Dec3-13",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/c9b67a1c-518c-43e4-b7d9-9438d42dcca3.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/5094cb9f-b7ce-45ca-abcc-aea927afe104.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e1fbf76a-5477-4330-a282-de0a4a11fb95.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/f69bdd3d-7cf5-4967-8c18-9399174214a4.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e9941284-2a71-48a8-a0c6-9c67d1c5f331.jpg?im_w=720",
    ],
    latlong: ["51.55830158266192", "5.419437777305826"],
    description:
      "Luxuriously furnished vacation home with all the comforts, made in a historic jacket.4 bedrooms, 2 bathrooms and a lovely private terrace directly adjacent to the horse meadows.De Oude Stal and De Woelige Stal are two separate vacation homes for each 4 people that can be linked by means of a large sliding wall to one large house: De Oude Woelige Stal for 8 people.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Tyrolean farmhouse with panoramic views",
    name: "Entire rental unit hosted by Sara",
    rating: 4.66,
    num_reviews: 67,
    city: "Vielsalm, Wallonie",
    country: "Belgium",
    price: 95,
    superhost: "false",
    host: "Sara",
    guests: 2,
    bedrooms: 1,
    beds: 2,
    bath: 1,
    date: "Nov22-27",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/e94d6428-8206-4dc6-b4a2-d299c2e22618.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/3228f1eb-ab6d-409c-8c83-33202fd7183a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-50006894/original/94fd3065-98a1-4c69-8eaf-64e512ee7cae.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/310951e5-360c-43be-b691-132f4809985d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8bc9bb30-a7e8-429a-8471-9b5250ee5d1e.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-50006894/original/46b76b6c-3f40-49e3-9508-e10942b25045.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-50006894/original/4b5f7f1d-564d-4094-8329-b22117ee4a97.jpeg?im_w=1200",
    ],
    latlong: ["50.26886695552791", "5.9059808029102445"],
    description:
      "The strengths of VLS Studio are above all its location, its facilities, its comfort and its atypical decoration.The apartment is located close to the city center, the train station and the lake of Vielsalm - Les Doyards Linen, necessary for cooking : all you have to do is put your bags down !Ideal for a romantic weekend, a few days of vacation or a business trip.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Beautiful nature. Close to Lakes & Hiking trails",
    name: "Entire rental unit hosted by Justin",
    rating: 4.82,
    num_reviews: 77,
    city: "London, England",
    country: "United Kingdom",
    price: 260,
    superhost: "false",
    host: "Justin",
    guests: 6,
    bedrooms: 3,
    beds: 2,
    bath: 2,
    date: "Dec1-18",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/8a695865-4b99-4d4c-908d-02030091bdae.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/d84dec18-b22a-4ab4-a62b-f9b1068666b8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4fe22984-eea1-42b8-b34b-fde6f6a4ed4d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/25af5223-5d8f-4cd1-b308-82382a12c4e6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ebe92836-06e6-4fa4-a776-b7ec551d30ef.jpg?im_w=720",
    ],
    latlong: ["51.52781023365028", "-0.14322171472229164"],
    description:
      "A stunning duplex, period conversion arranged over the top two floors of this impressive building in Little Venice, Central London.  The accommodation comprises entrance hall off which  master bedroom with en-suite bathroom, reception room with modern fireplace and open plan to a contemporary kitchen/breakfast room. A lovely modern spiral staircase leads up to the floor above with two good sized bedrooms and a modern shower room. The property also benefits from a private roof terrace.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Sleep in the middle of your garden",
    name: "Entire cabin hosted by Martin",
    rating: 4.91,
    num_reviews: 44,
    city: "Holbæk, Region Zealand ",
    country: "Denmark",
    price: 252,
    superhost: "true",
    host: "Martin",
    guests: 12,
    bedrooms: 3,
    beds: 8,
    bath: 1,
    date: "Dec7-22",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-14393977/original/c4ae9b1f-0945-4b6b-b769-6cab5cf87768.jpeg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-14393977/original/955e3761-9294-4e5b-ab36-2f4c0355240d.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/a348dd7f-b254-4d84-ad28-ebf2ccde2563.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ba1ea453-505c-45e5-ad9c-afc0aef41149.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e31890a3-7c8c-4fb8-ac09-f9b8a857d4ae.jpg?im_w=720",
    ],
    latlong: ["55.75809012961058", "11.711353940066243"],
    description:
      "The house is our second home, hobby and construction project.For 8 years, we have worked to make the house stand sharp and welcoming, thoughtful and delicious with a focus on ease of use and function.The new kitchen is the heart of the house and completely equipped with everything ( see table of contents below ) 100 m2 Rap round Terrace and 4 person SPA . Gas grill with equipment, sun loungers, cushions, blankets, outdoor fireplace that is good for outdoor fun and warmth.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Beautiful bali house with fireplace",
    name: "Private room in cave hosted by Sam",
    rating: 4.61,
    num_reviews: 54,
    city: "Göreme Belediyesi, Nevşehir",
    country: "Turkey",
    price: 125,
    superhost: "true",
    host: "Sam",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Nov28-30",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/3cf5662b-8eed-40f6-ab9b-9637b6631610.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/58d5afee-54e6-4c69-83ed-a1bb2046960e.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/521d5dda-85d4-4d99-84d2-159d43fcd4cc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/731276f0-37a4-473a-8a49-f9ed7e81a866.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ce5e65e7-036a-4a03-ad8b-0d0eba2d02f7.jpg?im_w=720",
    ],
    latlong: ["38.640622783217346", "34.83096944334566"],
    description:
      "Bringing a new level of eco-inspired chic to Göreme, Koza Cave is a masterclass in stylish sustainable tourism. Passionate owner Derviş spent decades living in Holland and has incorporated Dutch eco-sensibility into every cave crevice of the 10 stunning rooms. Grey water is reused, and recycled materials and local handcrafted furniture are utilised in abundance to create sophisticated spaces.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Sofia chalet",
    name: "Entire rental unit hosted by Linnea",
    rating: 4.71,
    num_reviews: 74,
    city: "Milano, Lombardia",
    country: "Italy",
    price: 453,
    superhost: "true",
    host: "Linnea",
    guests: 6,
    bedrooms: 3,
    beds: 5,
    bath: 2,
    date: "Nov30-Dec30",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/d45291aa-fdbb-4a86-a9af-34bee2e91ee2.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/74d97964-765a-4c14-9db2-6d8b29d128cf.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/07212ba2-916f-4c70-9a96-920dabd2340f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/74952862-bfc4-4515-b7bc-3029f74b41ae.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a2af8128-d767-4548-b2ea-ed33685b074c.jpg?im_w=720",
    ],
    latlong: ["45.46183294232915", " 9.196593496310898"],
    description:
      "The Penthouse you've always dreamed of is waiting for you in Milan! With its lavish rooftop garden and luxurious hot tub that overlooks the iconic Duomo cathedral, this brand new Penthouse has been designed with those who want to live their lives like royalty. You'll find her pristine rooms tranquil with tall windows that offer breathtaking views across the city. ",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Unique holiday home by the water for the family",
    name: "Entire loft hosted by Thomas",
    rating: 5,
    num_reviews: 148,
    city: "Gent, Vlaams Gewest",
    country: "Belgium",
    price: 111,
    superhost: "false",
    host: "Thomas",
    guests: 4,
    bedrooms: 2,
    beds: 4,
    bath: 1,
    date: "Nov26-29",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-33248221/original/8dd2344f-5f1d-4a15-95d4-f9cd0cdd3f7c.jpeg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-33248221/original/bdb1d931-fd55-4e03-904b-3e4d97bb4163.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-33248221/original/87ff4efa-3728-42dd-b5b7-402243c6392b.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-33248221/original/156284fe-a164-48de-89e3-c580e02df7fb.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-33248221/original/ed996df4-0fa1-4fbe-b49e-440dc598db25.jpeg?im_w=720",
    ],
    latlong: ["51.06242605229066", "3.7268429129683716"],
    description:
      "Spacious unique loft in the New York Loft Building. The building used to be a warehouse, constructed in 1913, in what was at that time a busy harbour area. Now it is the biggest protected city view of Ghent and becoming more and more a touristic hotspot. A really unique area! Free parking zone. ",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },
  {
    title: "Cozy holiday home with the most beautiful view",
    name: "Entire serviced apartment hosted by Eric",
    rating: 4.88,
    num_reviews: 675,
    city: "Hamburg",
    country: "Germany",
    price: 153,
    superhost: "true",
    host: "Eric",
    guests: 4,
    bedrooms: 1,
    beds: 2,
    bath: 1,
    date: "Nov15-18",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/97e21866-8b88-470c-9a77-5da6b3ae4b2e.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/7689cdaa-19d3-4847-a81c-be6135c72171.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/c72ee127-0291-4ca1-bf33-c1ff81e180cc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/43d9ab55-253e-46d3-9cb7-fc555d02fd3c.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/89d66f2b-4073-44a2-a578-a93d3d6df118.jpg?im_w=720",
    ],
    latlong: ["53.550115855938635", "10.005200246544712"],
    description:
      "Born in Copenhagen, architecture and design are my life. I regularly work with major Nordic design studios and during one of my trips, I stopped off in Barcelona: I was captivated by its architecture, culture and Mediterranean colour. Such was the impact the city had on me that I decided to stay and carry on my latest project: Eric Vökel Boutique Apartments. ",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Beautiful house in southern Brno",
    name: "Entire place hosted by Nataliia",
    rating: 4.33,
    num_reviews: 25,
    city: "Izky, Zakarpattia Oblast",
    country: "Ukraine",
    price: 69,
    superhost: "false",
    host: "Nataliia",
    guests: 4,
    bedrooms: 2,
    beds: 4,
    bath: 1,
    date: "Nov22-29",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/5e33c103-ab36-4a26-b52e-69343c8caaa9.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/f6c060d6-461f-4244-bae9-80997618d8d0.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-53784643/original/a9f2d905-4b54-49b5-b0a1-948ccf131864.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/0ddc0301-7ecb-4f9b-8fb5-6a4b0ef0b801.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-53784643/original/ae9f3586-a3ba-46a9-9838-a9afcf647f27.jpeg?im_w=720",
    ],
    latlong: ["48.64854472807008", "23.36667465786347"],
    description:
      "Enjoy the sounds of nature, incredible stairs, and sunsets right from your bed, and a great weekend away.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Lovely accommodation in Gunnarp",
    name: "Entire cabin hosted by Peishan",
    rating: 4.66,
    num_reviews: 179,
    city: "Kerhonkson, New York",
    country: "United States",
    price: 343,
    superhost: "true",
    host: "Peishan",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bath: 1,
    date: "Nov22-30",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/cd96b8b7-43c6-4030-8d70-22a78d419e4d.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/412e5605-79a7-4d99-941e-697cbbc63917.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8dde9e45-1653-4571-96bc-37eba84d9b0f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/bb793985-7a43-4354-a059-e4adbaeb9b09.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/f856ce68-2feb-4924-86e8-c83a5e413704.jpg?im_w=720",
    ],
    latlong: ["41.83259898991186", "-74.29981756649954"],
    description:
      "The Ashpine dream started with a love for beautiful spaces, an obsession with architecture and design, and a passion for hospitality.The new horizons of our dream is to help others create great memories, then eventually build more dream spaces in the forests of the Catskill Mountains and the Hudson Valley of NY. Thank you for the opportunity to share what we love.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Small and romantic blockhouse",
    name: "Houseboat hosted by Gabriela",
    rating: 4.4,
    num_reviews: 88,
    city: "Praha 5, Hlavní město Praha",
    country: "Czechia",
    price: 59,
    superhost: "true",
    host: "Gabriela",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bath: 1,
    date: "Nob16-28",
    type: "houseboat",
    images: [
      "https://a0.muscache.com/im/pictures/6295a03a-a745-44db-ad84-b69160297b47.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/1603a55f-e30e-472c-8204-ba2e1530a272.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ba6a926b-1545-4b84-9b07-37d029781d94.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/cffb2100-eda2-4dab-b97c-7c0bb2b4e7cc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ee3f84e3-8204-434b-aa33-5d5092e92541.jpg?im_w=720",
    ],
    latlong: ["50.05688753906348", "14.421038303367576"],
    description:
      "A new, modern and cosy houseboat, with two terraces, a bar on the waterfront, air conditioning and heating is waiting for You! Fully equipped boat for a cool stay in a great Prague location offers unique accommodation for a special break. Located close to subway, surrounded with nice and home atmosphere cafes, restaurants. Only 15 min. walk from popular sightseeing spots such as Dancing house, National theatre and others.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Holiday cottage",
    name: "Entire chalet hosted by Simas",
    rating: 5,
    num_reviews: 10,
    city: "Paplatelės, Plungės",
    country: "Lithuania",
    price: 103,
    superhost: "false",
    host: "Siams",
    guests: 4,
    bedrooms: 2,
    beds: 3,
    bath: 1,
    date: "Nov29-Dec15",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-49434096/original/3fcc350c-ac5f-4464-b757-4f43ef33c89f.jpeg?im_w=1200",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49434096/original/a65ad0ce-a614-4e30-827b-6d60b4a8954d.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49434096/original/8259d068-53b6-46c7-a70c-42e46ddf7895.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49434096/original/97836fa1-c200-4899-a9d8-a1d1b013f15c.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49434096/original/e8d503c0-2547-47fd-9d47-8fde53fb33e1.jpeg?im_w=720",
    ],
    latlong: ["56.05405656863985", "21.881672004555323"],
    description:
      "1.5 bedroom two level chalet ‘Gile’ is a newly restored ethnographic ranch located in Zemaitijos national park near the lake Plateliai, surrounded by the forest. You will enjoy private garden, hot tub in the terrace and amazing forest view.You will find many cool chill areas, jacuzzi-hot tubs, Horse riding centre, outdoor fire place etc. 200m away there is famous Paplateles tracking trail, 300m away there is bicycle track which can take you around the lake and much more.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Quiet and Gin at a Distillery at Ranch on a Lake",
    name: "Entire guest suite hosted by Pawel",
    rating: 4.99,
    num_reviews: 19,
    city: "Wałcz, Województwo zachodniopomorskie",
    country: "Poland",
    price: 77,
    superhost: "false",
    host: "Pawel",
    guests: 10,
    bedrooms: 3,
    beds: 7,
    bath: 2,
    date: "Nov30-Dec11",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/905e4f3b-caff-4317-bf7d-2460d649dd70.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/4f240915-110d-41b5-bbda-30d23852f79e.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/419cc27c-379c-433b-a1bf-0a3ea383adc6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e8eab9fd-7865-43df-81ca-b775cbc48480.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7d645390-f115-416c-989d-1f87ce2acfd4.jpg?im_w=720",
    ],
    latlong: ["53.270349936402546", "16.467557729837864"],
    description:
      "Apartment 34 is a very unique 3 level flat. It is entirely located in the historical water tower. Round walls of red brick, beautiful spiral stairs combined with modern equipment create a unique character of this apartment. An independent entrance ensures the privacy and comfort of our guests. Appartment has fully equipped kitchen,  2 bathrooms (bathtub & shower) and 2 bedrooms. Beds in the bedrooms can be set as double or as a twin + sofa bed (living)",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: "Pie Lielupe Apartments",
    name: "Entire rental unit hosted by Dmitry",
    rating: 4.55,
    num_reviews: 66,
    city: "Jūrmala, Jūrmalas pilsēta",
    country: "Latvia",
    price: 28,
    superhost: "false",
    host: "Dmitry",
    guests: 3,
    bedrooms: 0,
    beds: 3,
    bath: 1,
    date: "Nov16-26",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/75826604/19a9659a_original.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/75826818/801d4be7_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/75826967/31898d5e_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/76f0f483-275b-4ad7-ab4b-44bfaca5d134.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/943d715a-b072-4bd9-bf9b-4cfba2a12ab3.jpg?im_w=720",
    ],
    latlong: ["56.98835257196063", "23.875321756530553"],
    description:
      "Studio apartment. Nice view of the river. In the natural park. Opposite the beach, river, near the sea. Quiet Jurmala. The apartment has all the amenities - free internet WI-FI, a flat screen TV, stereo system. Bicycle rental.Studio apartment. Beautiful river view. In a nature park. Opposite the river beach, near the sea. Quiet Jurmala. All amenities of this apartment include free internet access.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },

  {
    title: " Row - Fun's Best Ocean View",
    name: "Entire cabin hosted by Leon And Carina",
    rating: 5,
    num_reviews: 14,
    city: "Martofte",
    country: "Denmark",
    price: 304,
    superhost: "false",
    host: "Catina and Leon",
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bath: 2,
    date: "Dec5-14",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/5973d706-c258-4818-b4d0-178508ad0739.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/3efc205f-b78b-461a-8f14-61cbac4630c1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/10d3ebc3-eb09-4c48-a670-906eaaa2ea1f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/57f0347a-74d6-4ad9-bad7-ea177b4e9d63.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/c2445fd0-5e6d-4920-82e2-1abd6413c468.jpg?im_w=720",
    ],
    latlong: ["55.597982233369294", "10.625598458221438"],
    description:
      "Funen's best location in first row with its own private condition - suitable for fishing and swimming trips. Better views of Storebælt are rarely available. This lovely 92m2 summer house also houses a nice living room with a stove, 3 bedrooms, 1 bath and an open kitchen for the dining room. In addition to a hilly garden, the house has a large terrace with reading screens. The home is a very well maintained Liljehus from 2000, but large window parties that make the home bright and inviting",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
      "Fantastic place and lovely flat with all necessities. It has great access to seaside and forest. There are three beds available with 4 headspace in total. We really enjoyed our stay.",
    ],
  },
  {
    title: "MyBlueCoast",
    name: "Entire condo hosted by Stella",
    rating: 4.77,
    num_reviews: 55,
    city: "Naxos",
    country: "Greece",
    price: 60,
    superhost: "true",
    host: "Stella",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Dec9-18",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/093ce60a-2ee0-4499-a77e-3d531110a132.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/4c30c087-7449-46f2-99ea-57d2296bcca8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/9c809728-ef64-4a04-b6dc-bd108d948c5a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/bcf7a03b-e61c-4ba5-8049-91207ed37bec.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/671a646a-1c0a-400c-8199-6b57d9ff20e3.jpg?im_w=720",
    ],
    latlong: ["37.038520180065206", "25.37951031907593"],
    description:
      "In Orkos area, the most beautiful region of Naxos with the amazing beaches, we have  MyBlueCoast by the sea with incredible view to the Aegean. Make your stay pleasant & unforgettable!",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "THE WAVE TWIN 1 INFINITY VILLA KATHISMA LEFKADA",
    name: "Entire villa hosted by Hristos",
    rating: 4,
    num_reviews: 800,
    city: "Kathisma Beach",
    country: "Greece",
    price: 221,
    superhost: "true",
    host: "Hristos",
    guests: 3,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Dec5-15",
    type: "lakefront",
    images: [
      "https://a0.muscache.com/im/pictures/2c6144b5-102b-4482-84a3-70026426a789.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/5f4e5992-5d2c-483b-9d98-e3f3e37b8633.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/20ee7611-1670-4058-a4a6-086cdb561a69.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e7c3b5ae-1d81-4678-a8f5-740df98ddb21.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/15ede273-06dd-4f3d-8571-8288ef82a540.jpg?im_w=720",
    ],
    latlong: ["38.77245780277549", "20.60275430615774"],
    description:
      "Newly built in 2021 with post on the west coast of Lefkada offers from all interior and exterior spaces unlimited spectacle the sea and sunset on the horizon. ",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Perla bungalov",
    name: "Entire bungalow hosted by Mehmetcan",
    rating: 4.55,
    num_reviews: 80,
    city: "Kartepe, Kocaeli",
    country: "Turkey",
    price: 221,
    superhost: "true",
    host: "Hristos",
    guests: 2,
    bedrooms: 2,
    beds: 1,
    bath: 1,
    date: "Dec22-31",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/cf7f3f57-8a00-4397-acea-c891760d4b2f.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/a5da5cb7-cac8-488f-85b1-a0dd78b28a86.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/c57b378e-8e11-4391-a33e-16c9906a7fcc.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/7a8689ed-068c-47ec-a5cd-15d0501c04da.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/eee7a580-ef2b-42a1-aff8-f98fcfec7383.jpg?im_w=480",
    ],
    latlong: ["40.708446871989295", "30.174114881609732"],
    description: "Stand-alone bungalow homes",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Geodesic Dome",
    name: "Dome hosted by Arsene",
    rating: 5,
    num_reviews: 25,
    city: "Râșnov Romacril, Județul Brașov",
    country: "Romania",
    price: 120,
    superhost: "false",
    host: "Arsene",
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bath: 1,
    date: "Dec1-11",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/e4827970-7f3b-4d10-abb2-1a4488cf79e6.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48267503/original/56788e1d-b6bc-48e3-863d-913db2134c1c.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48267503/original/403d065e-8bd4-405e-922b-f0888c58f019.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48267503/original/5d37ac33-4296-4843-aff1-4c365fd66faa.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/c52f12a2-71ab-4293-81c4-d8eaa32228b5.jpg?im_w=720",
    ],
    latlong: ["45.52287128933816", "25.445257565631007"],
    description:
      "Our Geodesic Dome was design to offer you not only accommodation, but a fully unique experience. Staying at our place will give you the feeling and peace of a wood cabin, the view of a mountain cabin, the intimacy of the woods, the commodity and space of a modern house with hot water, heat and electricity. Here, you will be on the grid but off the pavement.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Wassertheureralm for 6 persons",
    name: "Entire home hosted by Thomas",
    rating: 5,
    num_reviews: 4,
    city: "Dellach",
    country: "Austria",
    price: 131,
    superhost: "false",
    host: "Thomas",
    guests: 6,
    bedrooms: 2,
    beds: 4,
    bath: 2,
    date: "Dec7-14",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/prohost-api/Hosting-18535853/original/672673ca-2fdd-4feb-9a31-043a4f6b262f.jpeg?im_w=960",
      "https://a0.muscache.com/im/pictures/prohost-api/Hosting-18535853/original/eb13328b-b3ec-4664-ba7f-66d290c901d2.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/prohost-api/Hosting-18535853/original/0b13ca61-be64-4037-bba0-e35463942d2a.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/prohost-api/Hosting-18535853/original/707e44c0-9999-4f54-a605-530671ae8a35.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/prohost-api/Hosting-18535853/original/943e06ec-3804-43f3-a283-38fadf121a20.jpeg?im_w=480",
    ],
    latlong: ["46.760500678583085", "13.217730170800323"],
    description:
      "3-room chalet 120 m2 on 2 levels. Simple and rustic furnishings: living room with dining table. 1 double bedroom. Kitchen) with wood-burning stove. On the lower ground floor: shower/WC. Upper floor: 1 room with 3 double beds. Large patio. Marvellous panoramic view of the valley",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Waterfront with extraordinary view",
    name: "Entire rental unit hosted by Nela",
    rating: 4.2,
    num_reviews: 222,
    city: "Kotor, Kotor Municipality",
    country: "Montenegro",
    price: 141,
    superhost: "true",
    host: "Nela",
    guests: 4,
    bedrooms: 0,
    beds: 4,
    bath: 1,
    date: "Dec11-21",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/52159509/5acc860d_original.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/c0fb0725-d162-4673-ad34-c5c6c20504e9.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/7478b3b2-ef19-4d29-82db-100f96c7d3ee.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/89c24101-8626-4900-b24c-135e6b9f4811.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/89c24101-8626-4900-b24c-135e6b9f4811.jpg?im_w=480",
    ],
    latlong: ["42.49224075274944", "18.71109551830302"],
    description:
      "This charming, rustic studio apartment has a large private terrace with extraordinary view of the islands, equipped with outside dining table so you can enjoy your meals al fresco with a view. It is located right on the waterfront. There is one double bed and one sofa which is easily expandable to a double bed, so the apartment is perfect for couples or families with children. The bathroom is located downstairs, down a spiral staircase.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "All Ocean View Apartment - Nazare",
    name: "Entire rental unit hosted by João",
    rating: 5,
    num_reviews: 18,
    city: "Nazaré, Leiria",
    country: "Portugal",
    price: 107,
    superhost: "false",
    host: "João",
    guests: 5,
    bedrooms: 2,
    beds: 5,
    bath: 1,
    date: "Dec4-24",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/823f5d01-776c-44d7-97c4-0db6933326bb.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/987661ba-7c55-4f01-8079-07adbc14d7ef.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ab57a33a-de6f-4803-bc55-84f5144bcf61.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ed13fad5-5120-4691-b493-13f29a008dee.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/77930ce3-84d3-41e0-907d-8410e5aa3b05.jpg?im_w=720",
    ],
    latlong: ["39.59919762868705", "-9.068403943643078"],
    description:
      "In a quiet area of the village, the apartment features free parking nearb,you can find a supermarket 100 meters away. ",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "BNBHolder PALACIO DE CRISTAL es MIA",
    name: "Entire rental unit hosted by Emilio",
    rating: 4.44,
    num_reviews: 84,
    city: "Madrid, Comunidad de Madrid",
    country: "Spain",
    price: 117,
    superhost: "true",
    host: "Emilio",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Dec29-31",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/bac33416-c4dd-4da6-be0f-39fe4ea4ce13.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/ccb2d147-ef66-4c5e-b408-d246a6c3617b.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/61b2b824-d229-4205-a2b1-07c87c9683ca.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/0c84249e-66a4-4afc-aaeb-7209ae5896ce.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/20be561b-f3c3-4fa2-90b2-0894fd36afa0.jpg?im_w=480",
    ],
    latlong: ["40.41058041002167", "-3.6980686534521197"],
    description:
      "Stunning one bedroom designer apartment in the heart of Malasaña neighborhood, the castle neighborhood of the capital known for being the great witness to the Madrid Movida.Five minutes from the Gran Vía, the artery par excellence of the Madrid cultural board, and just ten minutes from Chueca.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Cave Granado Guadix Granada",
    name: "Cave hosted by Pepa Y Juan",
    rating: 4.9,
    num_reviews: 9,
    city: "Los Balcones, Andalucía",
    country: "Spain",
    price: 181,
    superhost: "false",
    host: "Pepa Y Juan",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bath: 2,
    date: "Dec10-20",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/108593327/77a7d32a_original.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/92d43f11-b58c-4306-8632-089d071b9799.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/c844000f-ebf3-4f5c-91d7-74404b2aac7a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/3064ab1e-bbb4-444b-b4e4-470263af1fa4.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/3f28259c-7551-4e41-9084-6045ee972edd.jpg?im_w=720",
    ],
    latlong: ["37.44285751875265", "-2.9392214143888657"],
    description:
      "The cave is fully equipped to live in it. It is in an old neighborhood that is being rehabilitated. It is for 5 people.The place is fascinating, a cannon overlooking the river Baul. Beautiful shared pool.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Amalfi Lady Laura House",
    name: "Entire rental unit hosted by Antonio",
    rating: 4.89,
    num_reviews: 231,
    city: "Amalfi, Campania",
    country: "Italy",
    price: 150,
    superhost: "true",
    host: "Antonio",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bath: 1,
    date: "Dec18-31",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/70c5ef55-4f7c-4e9a-8705-6b483c329616.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/748454fc-2df1-41e3-a875-c1d33d367a01.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/bff8945e-4e63-49b4-8ec0-31ec81f00061.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/6a4be995-f696-4c7a-b67b-4987d166cdba.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/7bf12f44-a8f6-44c9-968d-e9434784a467.jpg?im_w=480",
    ],
    latlong: ["40.63732646910345", "14.611966627076463"],
    description:
      "The apartment is located in the most characteristic area of Amalfi facing the sea with a wonderful panoramic view of the bay and the city, it is a 2 minute walk to the beach and Piazza Duomo, surrounded by typical bars and restaurants.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Seven Limits Wellness Guesthouse - Gerle",
    name: "Entire bungalow hosted by Ferenc",
    rating: 4.78,
    num_reviews: 150,
    city: "Pusztavacs",
    country: "Hungary",
    price: 124,
    superhost: "true",
    host: "Ferenc",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Nov18-28",
    type: "aframe",
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-744751138509112943/original/76585029-5a07-4f73-b588-238a63924653.jpeg?im_w=960",
      "https://a0.muscache.com/im/pictures/miso/Hosting-744751138509112943/original/244693b0-8d8d-4e62-a3b4-4ed7e4e16506.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/miso/Hosting-744751138509112943/original/a2dc562e-0523-45a1-8393-954e2da293dd.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/miso/Hosting-744751138509112943/original/09ad03f4-cd3b-4456-b8de-cd1450606475.jpeg?im_w=480",
      "https://a0.muscache.com/im/pictures/miso/Hosting-744751138509112943/original/c540fcbb-6ef2-4bf0-a9dc-7e4e8d45a25a.jpeg?im_w=480",
    ],
    latlong: ["47.18680417613474", "19.542496092644907"],
    description:
      "Just you, on the border of endless farmland.The Gerle houses are located in a 2.5-acre area surrounded by an artificial lake, ensuring good intimacy from each other.Breakfast is available upon request, and several restaurants deliver to us. The houses have a refrigerator, a grill, a microwave, a kettle, and a coffee maker (nescafe). The accommodation fee includes a love menu for dinner each.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Nature House-Bondo Valley Nature Reserve",
    name: "Farm stay hosted by Mara",
    rating: 4.65,
    num_reviews: 54,
    city: "Tremosine sul Garda, Brescia",
    country: "Italy",
    price: 151,
    superhost: "false",
    host: "Mara",
    guests: 3,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Nov15-19",
    type: "amazingview",
    images: [
      "https://a0.muscache.com/im/pictures/e69b3403-3d09-4f3f-b997-1a21164d1ee7.jpg?im_w=960",
      "https://a0.muscache.com/im/pictures/0abf4095-ef69-4afb-bef6-820e59d23990.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/52705e0f-e940-408f-a646-6bcb9adc8110.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/07b54251-f9b5-490e-8d0e-85afa65b161c.jpg?im_w=480",
      "https://a0.muscache.com/im/pictures/3429f983-5749-45a5-8c11-6a2e78606310.jpg?im_w=480",
    ],
    latlong: ["45.78285094876274", "10.714080048630256"],
    description:
      "Nature is what we are. Staying in the Valle di Bondo Nature Reserve, among wide meadows and green woods that dominate Lake Garda, is harmony. Far from the crowds, at 600m altitude, but close to its beaches, only 9km, Tremosine sul Garda offers breathtaking views, a peasant culture and lots of healthy sports. Pet-friendly means that we accept animals, but above all that we love them.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },

  {
    title: "Unique and Secluded AirShip with Breathtaking Highland Views",
    name: "Tiny home hosted by Amanda",
    rating: 4.88,
    num_reviews: 322,
    city: "Drimnin, Scotland",
    country: "United Kingdom",
    price: 188,
    superhost: "true",
    host: "Amanda",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bath: 1,
    date: "Dec18-27",
    type: "cabin",
    images: [
      "https://a0.muscache.com/im/pictures/4fb18cad-f0cc-4c15-a82c-eb6a400137a6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/fceeaee2-bbe7-4ba8-b0b8-06863e70017a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/0a0bfb9c-4a56-41e5-84f3-3558be01f3c5.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a855fd1a-7bee-4d8a-8c71-2e20e1647a20.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/3ef0bf91-afc0-4884-b2c8-13936778696a.jpg?im_w=240",
    ],
    latlong: ["56.60753129529046", "-5.974201206832139"],
    description:
      "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminum pod designed by Roderick James with views of the Sound of Mull from dragonfly windows. Airship002 is comfortable, quirky and cool. It does not pretend to be a five star hotel. The reviews tell the story. If booked for the dates you want check out our new listing The Pilot House, Drimnin which is on the same 4 acra site.",
    reviews: [
      "Perfect place to chill and enjoy the nature.The house is super beautiful and also the place in general.I Simply love it and will definitely come back!",
      "we are grateful for this magical stay on this houseboat with many wonderful moments...gladly again....",
      "We had a great time at Sebastians houseboat! I recommend to bring bikes.",
      "Very nice and relaxing location. Everything was perfect",
      "Everything was exactly as expected, the Interieur of the cabin is stunning, it was equipped with everything thats necessary. We can highly recommend this place. Perfect to relax and just wind down.",
    ],
  },
];

const LocalData = () => {
  const { state, dispatch } = useContext(Context);
  console.log(data);
  useEffect(() => {
    const getData = () => {
      return dispatch({ type: "localData", payload: data });
    };

    getData();
  }, [data]);
};

export default LocalData;
